package {packageName};

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;

/**
 * 创建{entityName}请求
 * 
 * @author Generated by java-rest-api-design skill
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "创建{entityName}请求")
public class Create{EntityName}Request {
    
    @NotBlank(message = "{fieldLabel}不能为空")
    @Size(min = {minLength}, max = {maxLength}, message = "{fieldLabel}长度必须在 {minLength}-{maxLength} 之间")
    @Schema(description = "{fieldLabel}", example = "{exampleValue}", required = true)
    private String {fieldName};
    
    // 添加更多字段...
}
