package {packageName};

import jakarta.validation.Constraint;
import jakarta.validation.ConstraintValidator;
import jakarta.validation.ConstraintValidatorContext;
import jakarta.validation.Payload;
import java.lang.annotation.*;

/**
 * 自定义校验器示例：{validatorName}
 * 
 * @author Generated by java-validation skill
 */
@Target({ElementType.FIELD, ElementType.PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
@Constraint(validatedBy = {ValidatorName}Validator.class)
@Documented
public @interface {ValidatorName} {
    
    String message() default "{validationMessage}";
    
    Class<?>[] groups() default {};
    
    Class<? extends Payload>[] payload() default {};
}

/**
 * 校验器实现
 */
class {ValidatorName}Validator implements ConstraintValidator<{ValidatorName}, String> {
    
    private static final String PATTERN = "{pattern}";
    
    @Override
    public void initialize({ValidatorName} constraintAnnotation) {
        // 初始化方法
    }
    
    @Override
    public boolean isValid(String value, ConstraintValidatorContext context) {
        if (value == null || value.isEmpty()) {
            return true;  // null 值由 @NotNull 等注解处理
        }
        return value.matches(PATTERN);
    }
}
