package {packageName}.controller;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import jakarta.validation.Valid;
import {packageName}.service.{EntityName}Service;
import {packageName}.dto.{EntityName}DTO;
import {packageName}.dto.request.Create{EntityName}Request;
import {packageName}.dto.request.Update{EntityName}Request;
import {packageName}.dto.request.PageRequest;
import {packageName}.dto.response.PageResult;
import {packageName}.dto.response.Result;

/**
 * {EntityName} Controller
 * 
 * @author Generated by java-mybatis-plus-generator skill
 */
@RestController
@RequestMapping("/api/v1/{entityPath}")
@Validated
@Slf4j
@RequiredArgsConstructor
public class {EntityName}Controller {
    
    private final {EntityName}Service {entityName}Service;
    
    /**
     * 查询单个{entityName}
     */
    @GetMapping("/{id}")
    public ResponseEntity<Result<{EntityName}DTO>> get{EntityName}(@PathVariable Long id) {
        log.info("查询{entityName}, id: {}", id);
        {EntityName}DTO {entityName} = {entityName}Service.getById(id);
        return ResponseEntity.ok(Result.success({entityName}));
    }
    
    /**
     * 创建{entityName}
     */
    @PostMapping
    public ResponseEntity<Result<{EntityName}DTO>> create{EntityName}(
            @Valid @RequestBody Create{EntityName}Request request) {
        log.info("创建{entityName}, request: {}", request);
        {EntityName}DTO {entityName} = {entityName}Service.create(request);
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(Result.success({entityName}));
    }
    
    /**
     * 更新{entityName}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Result<{EntityName}DTO>> update{EntityName}(
            @PathVariable Long id,
            @Valid @RequestBody Update{EntityName}Request request) {
        log.info("更新{entityName}, id: {}, request: {}", id, request);
        {EntityName}DTO {entityName} = {entityName}Service.update(id, request);
        return ResponseEntity.ok(Result.success({entityName}));
    }
    
    /**
     * 删除{entityName}
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Result<Void>> delete{EntityName}(@PathVariable Long id) {
        log.info("删除{entityName}, id: {}", id);
        {entityName}Service.delete(id);
        return ResponseEntity.ok(Result.success());
    }
    
    /**
     * 分页查询{entityName}列表
     */
    @GetMapping
    public ResponseEntity<Result<PageResult<{EntityName}DTO>>> list{EntityName}s(
            @Valid PageRequest pageRequest) {
        log.info("分页查询{entityName}, pageRequest: {}", pageRequest);
        PageResult<{EntityName}DTO> pageResult = {entityName}Service.list(pageRequest);
        return ResponseEntity.ok(Result.success(pageResult));
    }
}
