package {packageName}.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import {packageName}.entity.{EntityName};
import org.apache.ibatis.annotations.Mapper;

/**
 * {EntityName} Mapper 接口
 * 
 * @author Generated by java-mybatis-plus-generator skill
 */
@Mapper
public interface {EntityName}Mapper extends BaseMapper<{EntityName}> {
    
    // 自定义查询方法（如需要）
    // List<{EntityName}> selectCustomQuery(@Param("param") String param);
}
