package {packageName}.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import {packageName}.entity.{EntityName};
import {packageName}.mapper.{EntityName}Mapper;
import {packageName}.service.{EntityName}Service;
import {packageName}.dto.{EntityName}DTO;
import {packageName}.dto.request.Create{EntityName}Request;
import {packageName}.dto.request.Update{EntityName}Request;
import {packageName}.dto.request.PageRequest;
import {packageName}.dto.response.PageResult;
import {packageName}.converter.{EntityName}Converter;

import java.util.List;
import java.util.stream.Collectors;

/**
 * {EntityName} Service 实现类
 * 
 * @author Generated by java-mybatis-plus-generator skill
 */
@Service
@Slf4j
@RequiredArgsConstructor
public class {EntityName}ServiceImpl extends ServiceImpl<{EntityName}Mapper, {EntityName}> implements {EntityName}Service {
    
    private final {EntityName}Converter {entityName}Converter;
    
    @Override
    @Transactional(readOnly = true)
    public {EntityName}DTO getById(Long id) {
        log.info("查询{entityName}开始, id: {}", id);
        
        {EntityName} {entityName} = baseMapper.selectById(id);
        if ({entityName} == null) {
            // TODO: 替换为项目实际的异常处理方式
            throw new RuntimeException("{EntityName} not found, id: " + id);
        }
        
        log.info("查询{entityName}成功, id: {}", id);
        return {entityName}Converter.toDTO({entityName});
    }
    
    @Override
    @Transactional(rollbackFor = Exception.class)
    public {EntityName}DTO create(Create{EntityName}Request request) {
        log.info("创建{entityName}开始, request: {}", request);
        
        // 转换为实体
        {EntityName} {entityName} = {entityName}Converter.toEntity(request);
        
        // 保存
        boolean success = this.save({entityName});
        if (!success) {
            // TODO: 替换为项目实际的异常处理方式
            throw new RuntimeException("创建{entityName}失败");
        }
        
        log.info("创建{entityName}成功, id: {}", {entityName}.getId());
        return {entityName}Converter.toDTO({entityName});
    }
    
    @Override
    @Transactional(rollbackFor = Exception.class)
    public {EntityName}DTO update(Long id, Update{EntityName}Request request) {
        log.info("更新{entityName}开始, id: {}, request: {}", id, request);
        
        {EntityName} {entityName} = baseMapper.selectById(id);
        if ({entityName} == null) {
            // TODO: 替换为项目实际的异常处理方式
            throw new RuntimeException("{EntityName} not found, id: " + id);
        }
        
        // 更新字段
        {entityName}Converter.updateEntity({entityName}, request);
        
        // 保存
        boolean success = this.updateById({entityName});
        if (!success) {
            // TODO: 替换为项目实际的异常处理方式
            throw new RuntimeException("更新{entityName}失败");
        }
        
        log.info("更新{entityName}成功, id: {}", id);
        return {entityName}Converter.toDTO({entityName});
    }
    
    @Override
    @Transactional(rollbackFor = Exception.class)
    public void delete(Long id) {
        log.info("删除{entityName}开始, id: {}", id);
        
        boolean success = this.removeById(id);
        if (!success) {
            // TODO: 替换为项目实际的异常处理方式
            throw new RuntimeException("{EntityName} not found, id: " + id);
        }
        
        log.info("删除{entityName}成功, id: {}", id);
    }
    
    @Override
    @Transactional(readOnly = true)
    public PageResult<{EntityName}DTO> list(PageRequest pageRequest) {
        log.info("分页查询{entityName}开始, pageRequest: {}", pageRequest);
        
        // 使用 PageHelper 分页
        PageHelper.startPage(pageRequest.getPage(), pageRequest.getSize());
        
        // 构建查询条件
        LambdaQueryWrapper<{EntityName}> queryWrapper = new LambdaQueryWrapper<>();
        queryWrapper.eq({EntityName}::getDeleted, 0);  // 排除已删除
        
        // 排序
        if (pageRequest.getSortBy() != null) {
            if ("desc".equalsIgnoreCase(pageRequest.getSortOrder())) {
                queryWrapper.orderByDesc({EntityName}::getCreateTime);
            } else {
                queryWrapper.orderByAsc({EntityName}::getCreateTime);
            }
        }
        
        // 查询
        List<{EntityName}> list = this.list(queryWrapper);
        PageInfo<{EntityName}> pageInfo = new PageInfo<>(list);
        
        // 转换为 DTO
        List<{EntityName}DTO> content = list.stream()
                .map({entityName}Converter::toDTO)
                .collect(Collectors.toList());
        
        // 构建分页结果
        PageResult<{EntityName}DTO> pageResult = PageResult.<{EntityName}DTO>builder()
                .content(content)
                .total(pageInfo.getTotal())
                .page(pageRequest.getPage())
                .size(pageRequest.getSize())
                .totalPages(pageInfo.getPages())
                .hasPrevious(pageInfo.isHasPreviousPage())
                .hasNext(pageInfo.isHasNextPage())
                .isFirst(pageInfo.isIsFirstPage())
                .isLast(pageInfo.isIsLastPage())
                .build();
        
        log.info("分页查询{entityName}成功, total: {}", pageInfo.getTotal());
        return pageResult;
    }
}
