package {packageName}.service;

import com.baomidou.mybatisplus.extension.service.IService;
import {packageName}.entity.{EntityName};
import {packageName}.dto.{EntityName}DTO;
import {packageName}.dto.request.Create{EntityName}Request;
import {packageName}.dto.request.Update{EntityName}Request;
import {packageName}.dto.request.PageRequest;
import {packageName}.dto.response.PageResult;

/**
 * {EntityName} Service 接口
 * 
 * @author Generated by java-mybatis-plus-generator skill
 */
public interface {EntityName}Service extends IService<{EntityName}> {
    
    /**
     * 根据ID查询
     * @param id ID
     * @return {EntityName}DTO
     */
    {EntityName}DTO getById(Long id);
    
    /**
     * 创建
     * @param request 创建请求
     * @return {EntityName}DTO
     */
    {EntityName}DTO create(Create{EntityName}Request request);
    
    /**
     * 更新
     * @param id ID
     * @param request 更新请求
     * @return {EntityName}DTO
     */
    {EntityName}DTO update(Long id, Update{EntityName}Request request);
    
    /**
     * 删除
     * @param id ID
     */
    void delete(Long id);
    
    /**
     * 分页查询
     * @param pageRequest 分页请求
     * @return 分页结果
     */
    PageResult<{EntityName}DTO> list(PageRequest pageRequest);
}
