package {packageName};

/**
 * {entityName} Service 接口
 * 
 * @author Generated by java-service-layer skill
 */
public interface {EntityName}Service {
    
    /**
     * 根据ID查询{entityName}
     * @param id {entityName}ID
     * @return {entityName}信息
     * @throws BusinessException {entityName}不存在时抛出
     */
    {EntityName}DTO getById(Long id);
    
    /**
     * 创建{entityName}
     * @param request 创建请求
     * @return {entityName}信息
     * @throws BusinessException 业务校验失败时抛出
     */
    {EntityName}DTO create(Create{EntityName}Request request);
    
    /**
     * 更新{entityName}
     * @param id {entityName}ID
     * @param request 更新请求
     * @return {entityName}信息
     */
    {EntityName}DTO update(Long id, Update{EntityName}Request request);
    
    /**
     * 删除{entityName}
     * @param id {entityName}ID
     */
    void delete(Long id);
    
    /**
     * 分页查询{entityName}
     * @param pageRequest 分页请求
     * @return 分页结果
     */
    PageResult<{EntityName}DTO> list(PageRequest pageRequest);
}
