package {packageName};

import lombok.Getter;
import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;

/**
 * 错误码定义示例
 * 
 * @author Generated by java-exception-handling skill
 */
@Getter
@AllArgsConstructor
public enum ErrorCode {
    
    // ========== 通用错误码 ==========
    SUCCESS(200, "操作成功", HttpStatus.OK),
    PARAM_ERROR(400, "参数错误", HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(401, "未授权", HttpStatus.UNAUTHORIZED),
    FORBIDDEN(403, "无权限", HttpStatus.FORBIDDEN),
    NOT_FOUND(404, "资源不存在", HttpStatus.NOT_FOUND),
    SYSTEM_ERROR(500, "系统错误", HttpStatus.INTERNAL_SERVER_ERROR),
    
    // ========== 业务错误码 ==========
    // 用户相关
    USER_NOT_FOUND(1001, "用户不存在", HttpStatus.NOT_FOUND),
    USERNAME_ALREADY_EXISTS(1002, "用户名已存在", HttpStatus.BAD_REQUEST),
    
    // 订单相关
    ORDER_NOT_FOUND(2001, "订单不存在", HttpStatus.NOT_FOUND),
    ORDER_ITEMS_EMPTY(2002, "订单项不能为空", HttpStatus.BAD_REQUEST);
    
    private final Integer code;
    private final String message;
    private final HttpStatus httpStatus;
}
