package {packageName};

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

/**
 * {entityName} Service 实现类
 * 
 * @author Generated by java-service-layer skill
 */
@Service
@Slf4j
@RequiredArgsConstructor
public class {EntityName}ServiceImpl implements {EntityName}Service {
    
    private final {EntityName}Repository {entityName}Repository;
    private final {EntityName}Converter {entityName}Converter;
    
    @Override
    @Transactional(readOnly = true)
    public {EntityName}DTO getById(Long id) {
        log.info("查询{entityName}开始, id: {}", id);
        
        {EntityName} {entityName} = {entityName}Repository.findById(id)
                .orElseThrow(() -> {
                    log.warn("{entityName}不存在, id: {}", id);
                    return new BusinessException(ErrorCode.{ENTITY}_NOT_FOUND);
                });
        
        log.info("查询{entityName}成功, id: {}", id);
        return {entityName}Converter.toDTO({entityName});
    }
    
    @Override
    @Transactional(rollbackFor = Exception.class)
    public {EntityName}DTO create(Create{EntityName}Request request) {
        log.info("创建{entityName}开始, request: {}", request);
        
        try {
            // 业务校验
            validateCreate{EntityName}(request);
            
            // 业务逻辑处理
            {EntityName} {entityName} = {entityName}Converter.toEntity(request);
            {entityName}.setCreateTime(LocalDateTime.now());
            
            // 保存
            {EntityName} saved{EntityName} = {entityName}Repository.save({entityName});
            log.info("创建{entityName}成功, id: {}", saved{EntityName}.getId());
            
            return {entityName}Converter.toDTO(saved{EntityName});
            
        } catch (BusinessException e) {
            log.warn("创建{entityName}失败, error: {}", e.getMessage());
            throw e;
        } catch (Exception e) {
            log.error("创建{entityName}异常", e);
            throw new SystemException(ErrorCode.SYSTEM_ERROR, e);
        }
    }
    
    @Override
    @Transactional(rollbackFor = Exception.class)
    public {EntityName}DTO update(Long id, Update{EntityName}Request request) {
        log.info("更新{entityName}开始, id: {}, request: {}", id, request);
        
        {EntityName} {entityName} = {entityName}Repository.findById(id)
                .orElseThrow(() -> new BusinessException(ErrorCode.{ENTITY}_NOT_FOUND));
        
        // 更新字段
        {entityName}Converter.updateEntity({entityName}, request);
        {entityName}.setUpdateTime(LocalDateTime.now());
        
        {EntityName} updated{EntityName} = {entityName}Repository.save({entityName});
        log.info("更新{entityName}成功, id: {}", id);
        
        return {entityName}Converter.toDTO(updated{EntityName});
    }
    
    @Override
    @Transactional(rollbackFor = Exception.class)
    public void delete(Long id) {
        log.info("删除{entityName}开始, id: {}", id);
        
        if (!{entityName}Repository.existsById(id)) {
            throw new BusinessException(ErrorCode.{ENTITY}_NOT_FOUND);
        }
        
        {entityName}Repository.deleteById(id);
        log.info("删除{entityName}成功, id: {}", id);
    }
    
    @Override
    @Transactional(readOnly = true)
    public PageResult<{EntityName}DTO> list(PageRequest pageRequest) {
        log.info("分页查询{entityName}开始, pageRequest: {}", pageRequest);
        
        Pageable pageable = PageRequest.of(
                pageRequest.getPage() - 1,
                pageRequest.getSize(),
                Sort.by(Sort.Direction.fromString(pageRequest.getSortOrder()),
                        pageRequest.getSortBy())
        );
        
        Page<{EntityName}> page = {entityName}Repository.findAll(pageable);
        
        List<{EntityName}DTO> content = page.getContent().stream()
                .map({entityName}Converter::toDTO)
                .collect(Collectors.toList());
        
        return PageResult.<{EntityName}DTO>builder()
                .content(content)
                .total(page.getTotalElements())
                .page(pageRequest.getPage())
                .size(pageRequest.getSize())
                .totalPages(page.getTotalPages())
                .build();
    }
    
    /**
     * 校验创建{entityName}请求
     */
    private void validateCreate{EntityName}(Create{EntityName}Request request) {
        if (request == null) {
            throw new BusinessException(ErrorCode.PARAM_NULL, "请求参数不能为空");
        }
        // 更多业务校验...
    }
}
